// Generated by scripts/reviewer-capability-eval.ts from sealed live evidence.
export const PACKAGED_CAPABILITY_REVISION = {
  corpus_digest: 'f76edddd71868835e161d06987bce170fb395a71849412dd96c2b6d18c698b24',
  rubric_digest: 'b9d97005601dcaaa38caefb84716497d792170da6d5d4a0076b039691df9594f',
  settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
} as const;

export const PACKAGED_CAPABILITY_PAIRS = [
  {
    corpus_digest: 'f76edddd71868835e161d06987bce170fb395a71849412dd96c2b6d18c698b24',
    rubric_digest: 'b9d97005601dcaaa38caefb84716497d792170da6d5d4a0076b039691df9594f',
    settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
    author_provider: 'anthropic',
    author_model: 'claude-opus-5',
    reviewer_provider: 'openai',
    reviewer_model: 'gpt-6-astra',
    direction: 'not_weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-09-29',
    results_digest: '80cfc12c7eff986f7883df57f7d68168847b971a55c46306d039d6c1df552ea2',
  },
  {
    corpus_digest: 'f76edddd71868835e161d06987bce170fb395a71849412dd96c2b6d18c698b24',
    rubric_digest: 'b9d97005601dcaaa38caefb84716497d792170da6d5d4a0076b039691df9594f',
    settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
    author_provider: 'openai',
    author_model: 'gpt-6-astra',
    reviewer_provider: 'anthropic',
    reviewer_model: 'claude-opus-5',
    direction: 'weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-09-29',
    results_digest: '72348e3e6bcc1ac1a6de07c0f73c51f905ed635c6154be619b4ec51aaf26ae1b',
  },
] as const;
