// Generated by scripts/reviewer-capability-eval.ts from sealed live evidence.
export const PACKAGED_CAPABILITY_REVISION = {
  corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
  rubric_digest: 'f7a11ed5b1bca5f46e527892f2bfd2cefc77521e0bcede7974c5c6ea5e7aeb66',
  settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
} as const;

export const PACKAGED_CAPABILITY_PAIRS = [
  {
    corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
    rubric_digest: 'f7a11ed5b1bca5f46e527892f2bfd2cefc77521e0bcede7974c5c6ea5e7aeb66',
    settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
    author_provider: 'anthropic',
    author_model: 'claude-opus-5',
    reviewer_provider: 'openai',
    reviewer_model: 'gpt-6-astra',
    direction: 'not_weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-09-29',
    results_digest: '74a528e96f77e9fd7f54e5aefab8614346e0a464cdf1e6ecb3582d06077e8306',
  },
  {
    corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
    rubric_digest: 'f7a11ed5b1bca5f46e527892f2bfd2cefc77521e0bcede7974c5c6ea5e7aeb66',
    settings_digest: 'acd5a69993710ae8483c78771a67a6d61e061707f39f450a24a9a10511f7bf4d',
    author_provider: 'openai',
    author_model: 'gpt-6-astra',
    reviewer_provider: 'anthropic',
    reviewer_model: 'claude-opus-5',
    direction: 'not_weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-09-29',
    results_digest: '3afa536350b651124201e9c43be9908453dca7ab8c3afe5e6cb00991913d570b',
  },
] as const;
