// Generated by scripts/reviewer-capability-eval.ts from sealed live evidence.
export const PACKAGED_CAPABILITY_REVISION = {
  corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
  rubric_digest: 'a4662a8bb68e00b1da37f622ba88f2f0d8f9f3a502edea3777776ebb1d51cdc1',
  settings_digest: '5e89801fc75ed7f7e0a477a6ba32deca73cbe3896e6a640419aa7637f27c0e34',
} as const;

export const PACKAGED_CAPABILITY_PAIRS = [
  {
    corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
    rubric_digest: 'a4662a8bb68e00b1da37f622ba88f2f0d8f9f3a502edea3777776ebb1d51cdc1',
    settings_digest: '5e89801fc75ed7f7e0a477a6ba32deca73cbe3896e6a640419aa7637f27c0e34',
    author_provider: 'anthropic',
    author_model: 'claude-opus-5',
    reviewer_provider: 'openai',
    reviewer_model: 'gpt-6.1-sol',
    direction: 'not_weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-10-08',
    results_digest: '3ec4c7855b92ea12df5d86cc0554deee54fcd0ae999fe1d192997a37e280fc3b',
  },
  {
    corpus_digest: '9625362c688a1eb641c0a504cd75d1977c0f9ee05980c0e233a57a76bd99ba92',
    rubric_digest: 'a4662a8bb68e00b1da37f622ba88f2f0d8f9f3a502edea3777776ebb1d51cdc1',
    settings_digest: '5e89801fc75ed7f7e0a477a6ba32deca73cbe3896e6a640419aa7637f27c0e34',
    author_provider: 'openai',
    author_model: 'gpt-6.1-sol',
    reviewer_provider: 'anthropic',
    reviewer_model: 'claude-opus-5',
    direction: 'not_weaker',
    qualification: 'pinned-corpus',
    evidence_date: '2026-10-08',
    results_digest: 'de0148daaae8f9f877562af5abe369c3ab46b215f4a498c457ed48aad0cd757c',
  },
] as const;
