// Generated by scripts/generate-planning-contracts.ts. Do not edit.
import type { PlanningAuthorCopyIdentity, PlanningContract, PlanningPhase } from './phase-contract.js';

export const PLANNING_CONTRACTS = {
  "product-plan": {
    "phase": "product-plan",
    "purpose": "Define the accepted behavior and its product boundaries.",
    "entryCriteria": "Feature intake with the user's goal and current project context; a child also names its declared parent job and milestone.",
    "requiredContent": "The owning Product Plan or child Contribution, accepted Rules, scope and exclusions, observable done state, personas and affected surfaces. Keep supported facts, assumptions, and unresolved decisions distinct.",
    "prohibitedContent": "Implementation design, delivery task sequencing, or claims that scenarios, either downstream plan, or implementation are approved.",
    "reviewQuestion": "Does this Product Plan completely and honestly define the accepted behavior within user-owned scope, including its consequential outcomes?",
    "approvalMeaning": "The behavior is ready for scenario definition. This is not scenario acceptance, design approval, startable delivery, or completion.",
    "invalidation": "Changed Product Plan bytes or changed decision-bearing product boundaries require a current review of the changed decision.",
    "returnPath": "Repair incomplete behavior or unresolved product choices in intake, then review the corrected Product Plan before scenario definition."
  },
  "plan-implementation": {
    "phase": "plan-implementation",
    "purpose": "Decide a coherent implementation approach within accepted behavior.",
    "entryCriteria": "Accepted Product Plan Rules and scenarios, with current ticket and project boundaries, principles, personas, affected surfaces, dimensions when present, configured architecture records, and triggered data guidance.",
    "requiredContent": "Approach decisions, affected contracts and surfaces, concrete failure behavior, proof strategy and confidence limits, risks, rollout and rollback, recorded choices, and applicable architecture and data consequences.",
    "prohibitedContent": "Delivery task ordering, a second execution checklist, invented product scope, implementation results, or claims of downstream approval.",
    "reviewQuestion": "Is the accepted approach complete and coherent enough to sequence delivery without inventing another design or widening user-owned scope?",
    "approvalMeaning": "The approach is ready for Execution Planning. This does not approve delivery sequencing, coding, verification, merge, or deployment.",
    "invalidation": "Changed Implementation Plan bytes or decision-bearing behavior and scope require fresh approach review. Dependent Execution review follows the invalidation direction declared by its canonical owner.",
    "returnPath": "Repair approach decisions in Implementation Planning; unresolved product behavior returns to intake or scenario definition before fresh review."
  },
  "plan-execution": {
    "phase": "plan-execution",
    "purpose": "Turn the accepted approach into startable, dependency-ordered delivery.",
    "entryCriteria": "Current accepted Implementation Plan and scenarios, with current ticket and project boundaries, principles, personas, affected surfaces, dimensions when present, configured architecture records, and triggered data guidance.",
    "requiredContent": "Startable tasks and prerequisites, dependency order, concrete proof specifications, pull-request slicing, reviewed delivery obligations, honest evidence classes, and explicit pending human authority.",
    "prohibitedContent": "A competing approach, expanded product scope, unreviewed design choices, or completion claims unsupported by current real-boundary proof.",
    "reviewQuestion": "Can delivery start and finish from this sequence without inventing an approach, proof boundary, or additional scope?",
    "approvalMeaning": "The reviewed sequence authorizes its bounded coding work when the configured authority permits it. It does not establish implementation, verification, merge, promotion, or deployment completion.",
    "invalidation": "Load-bearing behavior or scope changes and accepted Implementation Plan changes invalidate both plan reviews. Execution-only decision changes invalidate its own review; ordinary checklist progress retains it. The upstream direction is `upstreamImplementationInvalidation: both_plan_reviews`.",
    "returnPath": "Repair sequencing in Execution Planning. A changed or missing accepted approach returns through Implementation Planning and dependent execution review.",
    "upstreamImplementationInvalidation": "both_plan_reviews"
  }
} as const satisfies Record<PlanningPhase, PlanningContract>;

export const PLANNING_AUTHOR_COPIES = {
  "product-plan": {
    "relativePath": "templates/skills/bdd/DISCOVERY.md",
    "sha256": "b914910e5cbdd04c6ec25f44315554a6382f974fc8c91c04ed56782758176922"
  },
  "plan-implementation": {
    "relativePath": "templates/skills/bdd/PLAN_IMPLEMENTATION.md",
    "sha256": "07129dce26ca9670ac3d6b3cbac3b0106474dec17aafd1a7c1295189b348d3d3"
  },
  "plan-execution": {
    "relativePath": "templates/skills/bdd/PLAN_EXECUTION.md",
    "sha256": "6f031383103dfe880a9c4cd5f14b8e7cf95989bafd579a9ae8450bb1d8216b53"
  }
} as const satisfies Record<PlanningPhase, PlanningAuthorCopyIdentity>;
