/**
 * SQL Language Pack - Schema Definitions
 *
 * All SQL-specific file definitions and config generators.
 * Imported by schema.ts and spread into SAFEWORD_SCHEMA.
 */

import type { FileDefinition, ManagedFileDefinition } from '../types.js';
import { detectSqlDialect } from './dialect.js';

// ============================================================================
// SQLFluff Configuration
// ============================================================================

/**
 * Shared SQLFluff rules for .safeword/sqlfluff.cfg.
 * Stricter rules for LLM enforcement — extends project config.
 */
const SQLFLUFF_STRICT_RULES = `[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
capitalisation_policy = upper

[sqlfluff:rules:layout.long_lines]
max_line_length = 120`;

// ============================================================================
// Config Generators for .safeword/ (ownedFiles)
// ============================================================================

/**
 * Generate SQLFluff config for .safeword/sqlfluff.cfg.
 *
 * If project has existing config, extends it with stricter rules.
 * Otherwise generates standalone config.
 */
function generateSqlfluffBaseConfig(
  existingSqlfluffConfig: string | undefined,
  dialect: string,
): string {
  if (existingSqlfluffConfig) {
    // Don't emit dialect or templater — let customer's config provide them.
    // sqlfluff --config patches key-by-key, so omitting means customer's values survive.
    return `# Safeword SQLFluff config - adds stricter rules on top of project config
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# Re-run \`safeword upgrade\` to regenerate after project config changes.
#
# NOTE: Your dialect and templater are preserved. Safeword only adds style rules.

[sqlfluff]
warnings =

${SQLFLUFF_STRICT_RULES}
`;
  }

  return `# Generated by safeword - DO NOT EDIT
# Customize by creating .sqlfluff at project root

[sqlfluff]
dialect = ${dialect}
templater = jinja
max_line_length = 120
warnings =

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

${SQLFLUFF_STRICT_RULES}
`;
}

// ============================================================================
// Owned Files (overwritten on upgrade)
// ============================================================================

export const sqlOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/sqlfluff.cfg': {
    generator: ctx =>
      ctx.languages?.sql
        ? generateSqlfluffBaseConfig(
            ctx.projectType.existingSqlfluffConfig,
            detectSqlDialect(ctx.cwd) ?? 'ansi',
          )
        : undefined,
  },
};

// ============================================================================
// Config Generators for project root (managedFiles)
// ============================================================================

function generateProjectSqlfluffConfig(dialect: string): string {
  return `# Generated by safeword
# Add your project-specific overrides here.
# Strict rules for LLM enforcement are in .safeword/sqlfluff.cfg

[sqlfluff]
dialect = ${dialect}
templater = jinja
max_line_length = 120

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
`;
}

// ============================================================================
// Managed Files (create if missing, reconciled on reset/upgrade)
// ============================================================================

export const sqlManagedFiles: Record<string, ManagedFileDefinition> = {
  '.sqlfluff': {
    generator: ctx =>
      ctx.languages?.sql && !ctx.projectType.existingSqlfluffConfig
        ? generateProjectSqlfluffConfig(detectSqlDialect(ctx.cwd) ?? 'ansi')
        : undefined,
  },
};
