/**
 * Rust language pack file definitions
 *
 * Defines config generators and file definitions for:
 * - clippy.toml (lint thresholds)
 * - rustfmt.toml (formatting options)
 */

import { existsSync, readFileSync } from 'node:fs';
import nodePath from 'node:path';

import type { FileDefinition, ManagedFileDefinition } from '../types.js';

// ============================================================================
// Shared Configuration Constants
// ============================================================================

/**
 * Safeword's clippy thresholds — fills gaps only, customer values win.
 *
 * Clippy defaults are lenient (cognitive-complexity = 25, args = 7).
 * Safeword tightens for LLM code but respects explicit customer choices.
 */
const SAFEWORD_CLIPPY_THRESHOLDS: Record<string, number> = {
  'cognitive-complexity-threshold': 10,
  'too-many-arguments-threshold': 5,
  'too-many-lines-threshold': 100,
  'type-complexity-threshold': 250,
};

// ============================================================================
// Config Generators
// ============================================================================

/** Generate standalone clippy.toml with safeword thresholds. */
function generateClippyConfig(): string {
  const thresholds = Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
    .map(([key, value]) => `${key} = ${String(value)}`)
    .join('\n');

  return `# Generated by safeword - DO NOT EDIT
# Configure lint levels in Cargo.toml [lints.clippy] section

${thresholds}
`;
}

/**
 * Generate .safeword/clippy.toml — fills gaps only.
 * Customer's thresholds are preserved; safeword only adds missing ones.
 */
function generateSafewordClippyConfig(existingConfig: string | undefined, cwd: string): string {
  if (!existingConfig) {
    return `# Safeword clippy config - standalone (no project config to merge)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }

  const configPath = nodePath.join(cwd, existingConfig);
  if (!existsSync(configPath)) {
    return `# Safeword clippy config - standalone (no project config to merge)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }

  try {
    const content = readFileSync(configPath, 'utf8');
    const customerKeys = parseClippyKeys(content);

    // Fill gaps: only add thresholds customer didn't set
    const gapEntries = Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
      .filter(([key]) => !customerKeys.has(key))
      .map(([key, value]) => `${key} = ${String(value)}`);

    // Include all customer content, then append safeword's gap-fills
    const safewordSection =
      gapEntries.length > 0
        ? `\n# Safeword defaults (not set in project config)\n${gapEntries.join('\n')}\n`
        : '';

    return `# Safeword clippy config - merged with project config
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# Re-run \`safeword upgrade\` to regenerate after project config changes.
#
# NOTE: Your thresholds are preserved. Safeword only fills gaps.

${content.trim()}
${safewordSection}`;
  } catch {
    return `# Safeword clippy config - standalone (parse error on project config)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }
}

/** Generate threshold lines from SAFEWORD_CLIPPY_THRESHOLDS. */
function generateClippyThresholds(): string {
  return Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
    .map(([key, value]) => `${key} = ${String(value)}`)
    .join('\n');
}

/** Parse a clippy.toml and return the set of keys that are defined. */
function parseClippyKeys(content: string): Set<string> {
  const keys = new Set<string>();
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const match = /^([\w-]+)\s*=/.exec(trimmed);
      if (match) keys.add(match[1]);
    }
  }
  return keys;
}

function generateRustfmtConfig(): string {
  return `# Generated by safeword - DO NOT EDIT
# Uses only stable options (works on all Rust toolchains)

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
use_field_init_shorthand = true
`;
}

// ============================================================================
// Owned Files (.safeword/ - overwritten on upgrade)
// ============================================================================

export const rustOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/clippy.toml': {
    generator: ctx =>
      ctx.languages?.rust
        ? generateSafewordClippyConfig(ctx.projectType.existingClippyConfig, ctx.cwd)
        : undefined,
  },
  '.safeword/rustfmt.toml': {
    generator: ctx => (ctx.languages?.rust ? generateRustfmtConfig() : undefined),
  },
};

// ============================================================================
// Managed Files (project root - create if missing)
// ============================================================================

export const rustManagedFiles: Record<string, ManagedFileDefinition> = {
  'clippy.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingClippyConfig
        ? generateClippyConfig()
        : undefined,
  },
  'rustfmt.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingRustfmtConfig
        ? generateRustfmtConfig()
        : undefined,
  },
};
