/**
 * Rust language pack file definitions
 *
 * Defines config generators and file definitions for:
 * - clippy.toml (lint thresholds)
 * - rustfmt.toml (formatting options)
 */

import { existsSync, readFileSync } from 'node:fs';
import nodePath from 'node:path';

import type { FileDefinition, ManagedFileDefinition } from '../types.js';

// ============================================================================
// Shared Configuration Constants
// ============================================================================

/**
 * Safeword's clippy thresholds — fills gaps only, customer values win.
 *
 * Clippy defaults are lenient (cognitive-complexity = 25, args = 7).
 * Safeword tightens for LLM code but respects explicit customer choices.
 */
const SAFEWORD_CLIPPY_THRESHOLDS: Record<string, number> = {
  'cognitive-complexity-threshold': 10,
  'too-many-arguments-threshold': 5,
  'too-many-lines-threshold': 100,
  'type-complexity-threshold': 250,
};

// ============================================================================
// Config Generators
// ============================================================================

/** Generate standalone clippy.toml with safeword thresholds. */
function generateClippyConfig(): string {
  const thresholds = Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
    .map(([key, value]) => `${key} = ${String(value)}`)
    .join('\n');

  return `# Generated by safeword - DO NOT EDIT
# Configure lint levels in Cargo.toml [lints.clippy] section

${thresholds}
`;
}

/**
 * Generate .safeword/clippy.toml — fills gaps only.
 * Customer's thresholds are preserved; safeword only adds missing ones.
 */
function generateSafewordClippyConfig(existingConfig: string | undefined, cwd: string): string {
  if (!existingConfig) {
    return `# Safeword clippy config - standalone (no project config to merge)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }

  const configPath = nodePath.join(cwd, existingConfig);
  if (!existsSync(configPath)) {
    return `# Safeword clippy config - standalone (no project config to merge)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }

  try {
    const content = readFileSync(configPath, 'utf8');
    const customerKeys = parseClippyKeys(content);

    // Fill gaps: only add thresholds customer didn't set
    const gapEntries = Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
      .filter(([key]) => !customerKeys.has(key))
      .map(([key, value]) => `${key} = ${String(value)}`);

    // Include all customer content, then append safeword's gap-fills
    const safewordSection =
      gapEntries.length > 0
        ? `\n# Safeword defaults (not set in project config)\n${gapEntries.join('\n')}\n`
        : '';

    return `# Safeword clippy config - merged with project config
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# Re-run \`safeword upgrade\` to regenerate after project config changes.
#
# NOTE: Your thresholds are preserved. Safeword only fills gaps.

${content.trim()}
${safewordSection}`;
  } catch {
    return `# Safeword clippy config - standalone (parse error on project config)
# Used by hooks for LLM enforcement.

${generateClippyThresholds()}
`;
  }
}

/** Generate threshold lines from SAFEWORD_CLIPPY_THRESHOLDS. */
function generateClippyThresholds(): string {
  return Object.entries(SAFEWORD_CLIPPY_THRESHOLDS)
    .map(([key, value]) => `${key} = ${String(value)}`)
    .join('\n');
}

/** Parse a clippy.toml and return the set of keys that are defined. */
function parseClippyKeys(content: string): Set<string> {
  const keys = new Set<string>();
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const match = /^([\w-]+)\s*=/.exec(trimmed);
      if (match?.[1]) keys.add(match[1]);
    }
  }
  return keys;
}

/**
 * Fallback Rust edition when the project's edition is truly unresolvable — an
 * unreadable/absent Cargo.toml, or a manifest with neither a `[package]` nor a
 * `[workspace.package]` edition to anchor to. Tracks the latest STABLE edition,
 * not the oldest: a fresh or unknowable project in 2026 is best served by the
 * current style edition (edition 2024, stable since Rust 1.85, 2025-02-20), not
 * a 2021 default that mis-sorts imports and can't parse 2024 syntax.
 */
const FALLBACK_RUST_EDITION = '2024';

/**
 * The edition Cargo assigns a `[package]` that declares none. We mirror it so an
 * edition-less (legacy) crate is formatted as the 2015 it actually is, rather
 * than having 2024 parsing/style imposed on 2015 code (which uses `async`,
 * `await`, `dyn`, `try` as identifiers).
 */
const CARGO_DEFAULT_EDITION = '2015';

/**
 * The `edition = "…"` value declared inside a named TOML section, or undefined.
 * Scoped to the section slice (header → next `[…]` header), comment-stripped,
 * and line-anchored so a `# edition = "2018"` comment or a `foo-edition` key
 * can't be mistaken for the real key. Accepts basic or literal TOML strings.
 */
function editionInSection(content: string, header: string): string | undefined {
  const start = content.indexOf(header);
  if (start === -1) return undefined;

  const rest = content.slice(start + header.length);
  const nextHeader = rest.search(/\n[ \t]*\[/);
  const section = nextHeader === -1 ? rest : rest.slice(0, nextHeader);

  for (const rawLine of section.split('\n')) {
    const line = rawLine.replace(/#.*/, '').trim();
    const match = /^edition\s*=\s*["']([^"']+)["']/.exec(line);
    if (match?.[1]) return match[1];
  }
  return undefined;
}

/**
 * Resolve the Rust edition to emit in rustfmt.toml by reading the project's
 * Cargo.toml. rustfmt's `edition` drives both parsing and (by default) the
 * style edition, and an explicit value in rustfmt.toml OVERRIDES what
 * `cargo fmt` would infer — so it must match the crate's real edition or it
 * mis-parses/mis-styles. Resolution order mirrors Cargo:
 *   1. `[package] edition`,
 *   2. workspace-inherited `[workspace.package] edition` (also the
 *      virtual-manifest case, where there is no `[package]`),
 *   3. a `[package]` that declares no edition → Cargo's 2015 default,
 *   4. otherwise the modern fallback (unreadable/absent manifest, or no edition
 *      anywhere to anchor to).
 * This never demands a newer toolchain than the crate already needs: a 2024
 * crate already requires Rust 1.85 to compile.
 */
export function resolveRustEdition(cwd: string): string {
  let content: string;
  try {
    content = readFileSync(nodePath.join(cwd, 'Cargo.toml'), 'utf8');
  } catch {
    return FALLBACK_RUST_EDITION;
  }

  const packageEdition = editionInSection(content, '[package]');
  if (packageEdition) return packageEdition;

  const workspaceEdition = editionInSection(content, '[workspace.package]');
  if (workspaceEdition) return workspaceEdition;

  // A present-but-edition-less `[package]` is edition 2015 by Cargo's default;
  // match it rather than imposing the modern fallback on legacy code. `.includes`
  // mirrors the pack's own `detectWorkspaceType` idiom.
  if (content.includes('[package]')) return CARGO_DEFAULT_EDITION;

  return FALLBACK_RUST_EDITION;
}

/**
 * Generate a lenient, forward-compatible `deny.toml` for the `cargo deny check`
 * supply-chain gate (`safeword test-plan --kind deps`, run at the /verify gate).
 *
 * Design choices, driven by cargo-deny's schema churn and the cost of a false
 * red on a customer's done-gate:
 * - Only long-lived fields; NO `version`/severity keys (`vulnerability`,
 *   `yanked`, …) — those were reshuffled across releases. cargo-deny denies
 *   advisories by default, so an explicit-but-empty `[advisories]` is enough and
 *   leaves an obvious place to add `ignore = ["RUSTSEC-…"]`.
 * - A BROAD permissive `allow` list (covers the overwhelming majority of
 *   crates.io) so the licenses check doesn't fail on a routine transitive dep the
 *   first time the gate runs. Users extend it when the gate flags a new license.
 * - `multiple-versions = "warn"` — duplicate versions are bloat, not a hard stop.
 */
function generateDenyConfig(): string {
  return `# Generated by safeword — cargo-deny dependency config.
# Safeword creates this file if missing and won't overwrite your edits.
# Full schema: https://embarkstudios.github.io/cargo-deny/checks/cfg.html
#
# The /verify done-gate runs ONLY the advisories check (\`cargo deny check
# advisories\`) — the universal security signal. The licenses/bans/sources
# sections below are configured but NOT gated by default, because they false-red
# on things unrelated to a change (missing license metadata, intentional git
# deps). Enforce them in your own CI with a full \`cargo deny check\`.

[advisories]
# Security advisories from the RustSec DB (the cargo-audit source). cargo-deny
# denies vulnerabilities by default; add \`ignore = ["RUSTSEC-YYYY-NNNN"]\` to
# accept a specific one with a rationale.

[licenses]
# Permissive licenses covering the vast majority of crates.io. Extend this list
# when the gate flags a dependency whose license you accept.
allow = [
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "ISC",
  "Zlib",
  "MPL-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "Unlicense",
  "BSL-1.0",
  "OpenSSL",
]

[bans]
# Duplicate versions bloat builds but rarely warrant a hard failure — warn only.
multiple-versions = "warn"

[sources]
# Trust only crates.io by default; flag crates pulled from unknown registries.
unknown-registry = "deny"
unknown-git = "deny"
`;
}

function generateRustfmtConfig(cwd: string): string {
  const edition = resolveRustEdition(cwd);
  return `# Generated by safeword - DO NOT EDIT
# edition is derived from your Cargo.toml (fallback: ${FALLBACK_RUST_EDITION}); it
# must match the crate's edition because rustfmt.toml overrides what cargo fmt infers.
# All other options are stable on any toolchain that supports this edition.

edition = "${edition}"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
use_field_init_shorthand = true
`;
}

// ============================================================================
// Owned Files (.safeword/ - overwritten on upgrade)
// ============================================================================

export const rustOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/clippy.toml': {
    generator: ctx =>
      ctx.languages?.rust
        ? generateSafewordClippyConfig(ctx.projectType.existingClippyConfig, ctx.cwd)
        : undefined,
  },
  '.safeword/rustfmt.toml': {
    generator: ctx => (ctx.languages?.rust ? generateRustfmtConfig(ctx.cwd) : undefined),
  },
};

// ============================================================================
// Managed Files (project root - create if missing)
// ============================================================================

export const rustManagedFiles: Record<string, ManagedFileDefinition> = {
  'clippy.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingClippyConfig
        ? generateClippyConfig()
        : undefined,
  },
  'rustfmt.toml': {
    generator: ctx =>
      ctx.languages?.rust && !ctx.projectType.existingRustfmtConfig
        ? generateRustfmtConfig(ctx.cwd)
        : undefined,
  },
  // deny.toml is create-if-missing (managed): the `cargo deny check` supply-chain
  // gate reads it from the project root. Never overwrites a user's own config.
  'deny.toml': {
    generator: ctx => (ctx.languages?.rust ? generateDenyConfig() : undefined),
  },
};
