/**
 * dbt Language Pack - Schema Definitions
 *
 * All dbt-specific file definitions and config generators.
 * Imported by schema.ts and spread into SAFEWORD_SCHEMA.
 */

import type { FileDefinition, ManagedFileDefinition } from '../types.js';

// ============================================================================
// SQLFluff Configuration
// ============================================================================

/**
 * Shared SQLFluff rules for .safeword/sqlfluff.cfg.
 * Stricter rules for LLM enforcement — extends project config.
 */
const SQLFLUFF_STRICT_RULES = `[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.identifiers]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = upper

[sqlfluff:rules:capitalisation.types]
capitalisation_policy = upper

[sqlfluff:rules:layout.long_lines]
max_line_length = 120`;

// ============================================================================
// Config Generators for .safeword/ (ownedFiles)
// ============================================================================

/**
 * Generate SQLFluff config for .safeword/sqlfluff.cfg.
 *
 * If project has existing config, extends it with stricter rules.
 * Otherwise generates standalone config.
 */
function generateSqlfluffBaseConfig(existingSqlfluffConfig: string | undefined): string {
  if (existingSqlfluffConfig) {
    return `# Safeword SQLFluff config - extends project config with stricter rules
# Used by hooks for LLM enforcement. Human pre-commits use project config.

[sqlfluff]
# Inherit from project config — add stricter overrides below

${SQLFLUFF_STRICT_RULES}
`;
  }

  return `# Generated by safeword - DO NOT EDIT
# Customize by creating .sqlfluff at project root

[sqlfluff]
dialect = ansi
templater = jinja
max_line_length = 120

${SQLFLUFF_STRICT_RULES}
`;
}

// ============================================================================
// Owned Files (overwritten on upgrade)
// ============================================================================

export const dbtOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/sqlfluff.cfg': {
    generator: ctx =>
      ctx.languages?.dbt
        ? generateSqlfluffBaseConfig(ctx.projectType.existingSqlfluffConfig)
        : undefined,
  },
};

// ============================================================================
// Config Generators for project root (managedFiles)
// ============================================================================

/**
 * Generate .sqlfluff for project root.
 * Basic config with ansi dialect and jinja templater for dbt.
 */
function generateProjectSqlfluffConfig(): string {
  return `# Generated by safeword
# Add your project-specific overrides here.
# Strict rules for LLM enforcement are in .safeword/sqlfluff.cfg

[sqlfluff]
dialect = ansi
templater = jinja
max_line_length = 120
`;
}

// ============================================================================
// Managed Files (create if missing, reconciled on reset/upgrade)
// ============================================================================

export const dbtManagedFiles: Record<string, ManagedFileDefinition> = {
  '.sqlfluff': {
    generator: ctx =>
      ctx.languages?.dbt && !ctx.projectType.existingSqlfluffConfig
        ? generateProjectSqlfluffConfig()
        : undefined,
  },
};
