/**
 * Derive the set of top-level path prefixes that safeword may write to,
 * sourced from SAFEWORD_SCHEMA at build time. Consumed by the auto-upgrade
 * hook to identify files to stage after `safeword upgrade` runs.
 *
 * Why this exists: the hook previously hardcoded the prefix list, which
 * silently drifts when a pack introduces a new top-level directory.
 *
 * Matching semantics: dir prefixes (trailing `/`) match by `startsWith`;
 * bare file paths match by exact equality. The generated module exports
 * both the flat list and an `isSafewordPath(file)` helper that uses these
 * semantics.
 */

/**
 * The structural subset of SAFEWORD_SCHEMA this module needs. Declared locally
 * (not imported from ./schema.js) to keep this file a sink in the dep graph —
 * schema.ts imports from here, so importing schema's types here would cycle.
 */
export interface SchemaPathBuckets {
  ownedFiles: Record<string, unknown>;
  managedFiles: Record<string, unknown>;
  jsonMerges: Record<string, unknown>;
  textPatches: Record<string, unknown>;
}

export function computeSafewordPathPrefixes(schema: SchemaPathBuckets): readonly string[] {
  const allPaths = [
    ...Object.keys(schema.ownedFiles),
    ...Object.keys(schema.managedFiles),
    ...Object.keys(schema.jsonMerges),
    ...Object.keys(schema.textPatches),
  ];

  const prefixes = new Set<string>();
  for (const path of allPaths) {
    const slashIndex = path.indexOf('/');
    prefixes.add(slashIndex === -1 ? path : path.slice(0, slashIndex + 1));
  }

  return [...prefixes].toSorted((a, b) => a.localeCompare(b));
}

/**
 * Reference implementation of the matching predicate. The generated module's
 * `isSafewordPath` is a closure over SAFEWORD_PATHS that runs this same logic.
 * Extracted so tests can verify semantics without evaluating generated code.
 */
export function matchesSafewordPath(file: string, prefixes: readonly string[]): boolean {
  for (const prefix of prefixes) {
    if (prefix.endsWith('/')) {
      if (file.startsWith(prefix)) return true;
    } else if (file === prefix) {
      return true;
    }
  }
  return false;
}

/**
 * Reference implementation of the auto-upgrade staging filter. Mirrors the
 * `filterSafewordFiles` exported from the generated module so tests can
 * exercise the exact behavior the hook relies on.
 */
export function referenceFilterSafewordFiles(
  changedFiles: readonly string[],
  untrackedFiles: readonly string[],
  prefixes: readonly string[],
): readonly string[] {
  return [...changedFiles, ...untrackedFiles].filter(f => matchesSafewordPath(f, prefixes));
}

export function generateOwnedPathsModule(schema: SchemaPathBuckets): string {
  const prefixes = computeSafewordPathPrefixes(schema);
  const entries = prefixes.map(prefix => `  '${prefix}',`).join('\n');

  return `// Auto-generated by safeword from SAFEWORD_SCHEMA. Do not edit by hand.
// Source: ownedFiles ∪ managedFiles ∪ jsonMerges ∪ textPatches → top-level prefixes.
// Regenerated on every \`safeword setup\` and \`safeword upgrade\`.

export const SAFEWORD_PATHS: readonly string[] = [
${entries}
];

/**
 * Match a file path against the safeword-managed set. Directory prefixes
 * (entries ending in \`/\`) match by \`startsWith\`; bare file paths must
 * match exactly so e.g. \`package.json.bak\` does not match \`package.json\`.
 */
export function isSafewordPath(file: string): boolean {
  for (const prefix of SAFEWORD_PATHS) {
    if (prefix.endsWith('/')) {
      if (file.startsWith(prefix)) return true;
    } else if (file === prefix) {
      return true;
    }
  }
  return false;
}

/**
 * Pick the safeword-managed subset of files reported by \`git diff --name-only\`
 * (changed) and \`git ls-files --others --exclude-standard\` (untracked).
 * Used by the auto-upgrade hook to decide what to stage after \`safeword upgrade\`.
 */
export function filterSafewordFiles(
  changedFiles: readonly string[],
  untrackedFiles: readonly string[],
): readonly string[] {
  return [...changedFiles, ...untrackedFiles].filter(f => isSafewordPath(f));
}
`;
}
