/**
 * Derive the set of top-level path prefixes that safeword may write to,
 * sourced from SAFEWORD_SCHEMA at build time. Consumed by the auto-upgrade
 * hook to identify files to stage after `safeword upgrade` runs.
 *
 * Why this exists: the hook previously hardcoded the prefix list, which
 * silently drifts when a pack introduces a new top-level directory.
 */

import type { SafewordSchema } from './schema.js';

export function computeSafewordPathPrefixes(schema: SafewordSchema): readonly string[] {
  const allPaths = [
    ...Object.keys(schema.ownedFiles),
    ...Object.keys(schema.managedFiles),
    ...Object.keys(schema.jsonMerges),
    ...Object.keys(schema.textPatches),
  ];

  const prefixes = new Set<string>();
  for (const path of allPaths) {
    const slashIndex = path.indexOf('/');
    prefixes.add(slashIndex === -1 ? path : path.slice(0, slashIndex + 1));
  }

  return [...prefixes].toSorted((a, b) => a.localeCompare(b));
}

export function generateOwnedPathsModule(schema: SafewordSchema): string {
  const prefixes = computeSafewordPathPrefixes(schema);
  const entries = prefixes.map(prefix => `  '${prefix}',`).join('\n');

  return `// Auto-generated by safeword from SAFEWORD_SCHEMA. Do not edit by hand.
// Source: ownedFiles ∪ managedFiles ∪ jsonMerges ∪ textPatches → top-level prefixes.
// Regenerated on every \`safeword setup\` and \`safeword upgrade\`.

export const SAFEWORD_PATHS: readonly string[] = [
${entries}
];
`;
}
