/**
 * Go Language Pack - Schema Definitions
 *
 * All Go-specific file definitions and config generators.
 * Imported by schema.ts and spread into SAFEWORD_SCHEMA.
 *
 * Mirrors the structure of typescript/files.ts and python/files.ts for consistency.
 */

import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import YAML from 'yaml';

import { exists } from '../../utils/fs.js';
import type { FileDefinition, ManagedFileDefinition } from '../types.js';

// ============================================================================
// Shared Configuration Constants
// ============================================================================

/**
 * Curated linter set — covers bugs, security, complexity, and modern Go
 * without the upgrade-breakage of `default: all`.
 *
 * Convention: `default: standard` + explicit `enable` list.
 * Used by golangci-lint itself, Docker, Prometheus, and the maratori golden config.
 */
const SAFEWORD_ENABLE = [
  // Bug detection
  'bodyclose', // unclosed HTTP response bodies
  'nilerr', // returning nil after checking err != nil
  'sqlclosecheck', // unclosed sql.Rows/Stmt
  'rowserrcheck', // unchecked sql.Rows.Err()
  'noctx', // HTTP requests without context
  'reassign', // reassigning top-level variables

  // Code quality
  'cyclop', // cyclomatic complexity (max 10 default)
  'nestif', // nested if depth
  'gocognit', // cognitive complexity
  'unconvert', // unnecessary type conversions
  'unparam', // unused function parameters
  'usestdlibvars', // use stdlib constants (http.StatusOK, etc.)
  'wastedassign', // wasted variable assignments
  'prealloc', // preallocate slice capacity

  // Security
  'gosec', // security issues

  // Style (low noise)
  'goconst', // repeated strings -> constants
  'misspell', // spelling in comments/strings
  'errorlint', // error wrapping conventions
  'gocritic', // opinionated but high-signal
  'revive', // flexible metalinter
  'perfsprint', // faster string formatting
  'copyloopvar', // loop variable capture (Go 1.22+)
  'intrange', // integer range loops (Go 1.22+)
];

/** Linters to disable (too strict or deprecated) */
const SAFEWORD_DISABLE = [
  'forbidigo', // blocks all print statements
  'wsl', // deprecated in v2.2.0, replaced by wsl_v5
];

/** Exclusion presets for common false positives */
const SAFEWORD_EXCLUSION_PRESETS = ['std-error-handling', 'common-false-positives'];

/** Safeword linter settings (only fills gaps — customer settings win) */
const SAFEWORD_SETTINGS: Record<string, Record<string, unknown>> = {
  nestif: { 'min-complexity': 4 },
};

// ============================================================================
// Config Generators
// ============================================================================

/** Build standalone golangci-lint v2 config object. */
function buildStandaloneConfig(): Record<string, unknown> {
  return {
    version: '2',
    linters: {
      default: 'standard',
      enable: [...SAFEWORD_ENABLE],
      disable: [...SAFEWORD_DISABLE],
      exclusions: { presets: [...SAFEWORD_EXCLUSION_PRESETS] },
      settings: structuredClone(SAFEWORD_SETTINGS),
    },
    formatters: { enable: ['gofumpt'] },
  };
}

/**
 * Generate golangci-lint v2 configuration for project root.
 * Created only when no existing config exists.
 */
function generateGolangciConfig(): string {
  const header = `# Generated by safeword - DO NOT EDIT
# To customize, add overrides below the formatters section

`;
  return header + YAML.stringify(buildStandaloneConfig());
}

/**
 * Generate safeword golangci-lint configuration for .safeword/.golangci.yml.
 *
 * If project has existing config, merges additively (preserves customer choices).
 * Handles both v1 and v2 config formats.
 */
function generateSafewordGolangciConfig(existingConfig: string | undefined, cwd: string): string {
  if (!existingConfig) {
    return getSafewordGolangciStandalone();
  }

  const configPath = nodePath.join(cwd, existingConfig);
  if (!exists(configPath)) {
    return getSafewordGolangciStandalone();
  }

  try {
    const projectContent = readFileSync(configPath, 'utf8');
    const projectConfig = YAML.parse(projectContent) as Record<string, unknown> | undefined;

    if (!projectConfig) {
      return getSafewordGolangciStandalone();
    }

    return projectConfig.version === '2'
      ? getSafewordGolangciMergedV2(projectConfig)
      : getSafewordGolangciMergedV1(projectConfig);
  } catch {
    console.warn(`Safeword: Could not parse ${existingConfig}, using standalone config`);
    return getSafewordGolangciStandalone();
  }
}

/** Standalone safeword golangci-lint config (v2 format) */
function getSafewordGolangciStandalone(): string {
  const header = `# Safeword golangci-lint config - standalone (no project config to merge)
# Used by hooks for LLM enforcement.

`;
  return header + YAML.stringify(buildStandaloneConfig());
}

// ============================================================================
// Additive Merge Helpers
// ============================================================================

/** Additively merge the v2 linters section — preserves customer choices. */
function mergeLinters(projectLinters: Record<string, unknown>): Record<string, unknown> {
  const customerExclusions = (projectLinters.exclusions as Record<string, unknown>) || {};
  const customerPresets = (customerExclusions.presets as string[]) || [];
  const customerSettings = (projectLinters.settings as Record<string, unknown>) || {};

  return {
    ...projectLinters,
    default: (projectLinters.default as string) || 'standard',
    enable: unionArrays((projectLinters.enable as string[]) || [], SAFEWORD_ENABLE),
    disable: unionArrays((projectLinters.disable as string[]) || [], SAFEWORD_DISABLE),
    exclusions: {
      ...customerExclusions,
      presets: unionArrays(customerPresets, SAFEWORD_EXCLUSION_PRESETS),
    },
    settings: fillGapMerge(customerSettings, SAFEWORD_SETTINGS),
  };
}

/** Additively merge formatters — append gofumpt if missing. */
function mergeFormatters(projectFormatters: Record<string, unknown>): Record<string, unknown> {
  const enable = (projectFormatters.enable as string[]) || [];
  return {
    ...projectFormatters,
    enable: enable.includes('gofumpt') ? enable : [...enable, 'gofumpt'],
  };
}

// ============================================================================
// Additive Merge (v2)
// ============================================================================

/** Merge project v2 config with safeword rules — additive, customer preserved. */
function getSafewordGolangciMergedV2(projectConfig: Record<string, unknown>): string {
  const merged: Record<string, unknown> = {
    ...projectConfig,
    version: '2',
    linters: mergeLinters((projectConfig.linters as Record<string, unknown>) || {}),
    formatters: mergeFormatters((projectConfig.formatters as Record<string, unknown>) || {}),
  };

  const header = `# Safeword golangci-lint config - merged with project config
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# Re-run \`safeword upgrade\` to regenerate after project config changes.
#
# NOTE: Safeword adds linters via 'enable' without changing your 'default'.
# Your disable list and exclusion presets are preserved (union, not replaced).

`;

  return header + YAML.stringify(merged);
}

// ============================================================================
// Additive Merge (v1 — legacy)
// ============================================================================

/** Merge project v1 config — additive, customer preserved. Outputs v1 format. */
function getSafewordGolangciMergedV1(projectConfig: Record<string, unknown>): string {
  const merged: Record<string, unknown> = { ...projectConfig };
  const projectLinters = (projectConfig.linters as Record<string, unknown>) || {};

  merged.linters = {
    ...projectLinters,
    enable: unionArrays((projectLinters.enable as string[]) || [], SAFEWORD_ENABLE),
    disable: unionArrays((projectLinters.disable as string[]) || [], SAFEWORD_DISABLE),
  };

  const projectSettings = (projectConfig['linters-settings'] as Record<string, unknown>) || {};
  merged['linters-settings'] = fillGapMerge(projectSettings, {
    nestif: { 'min-complexity': 4 },
    gofumpt: { 'extra-rules': true },
  });

  const header = `# Safeword golangci-lint config - merged with project config (v1 format)
# Used by hooks for LLM enforcement. Human pre-commits use project config.
# NOTE: Consider migrating to golangci-lint v2 format.
# Re-run \`safeword upgrade\` to regenerate after project config changes.

`;

  return header + YAML.stringify(merged);
}

// ============================================================================
// Merge Utilities
// ============================================================================

/** Union two string arrays, preserving order (base first), deduplicated. */
function unionArrays(base: string[], additions: string[]): string[] {
  const set = new Set(base);
  for (const item of additions) {
    set.add(item);
  }
  return [...set];
}

/**
 * Fill-gap merge: base (customer) wins on conflict, override fills missing keys.
 * For nested objects, recurses. Arrays are NOT replaced — customer's win.
 */
function fillGapMerge(
  base: Record<string, unknown>,
  defaults: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...base };

  for (const [key, defaultValue] of Object.entries(defaults)) {
    if (!(key in result)) {
      result[key] = defaultValue;
    } else if (
      defaultValue &&
      typeof defaultValue === 'object' &&
      !Array.isArray(defaultValue) &&
      result[key] &&
      typeof result[key] === 'object' &&
      !Array.isArray(result[key])
    ) {
      result[key] = fillGapMerge(
        result[key] as Record<string, unknown>,
        defaultValue as Record<string, unknown>,
      );
    }
  }

  return result;
}

// ============================================================================
// Owned Files (overwritten on upgrade)
// ============================================================================

export const golangOwnedFiles: Record<string, FileDefinition> = {
  '.safeword/.golangci.yml': {
    generator: ctx =>
      ctx.languages?.golang
        ? generateSafewordGolangciConfig(ctx.projectType.existingGolangciConfig, ctx.cwd)
        : undefined,
  },
};

// ============================================================================
// Managed Files (create if missing, update if matches template)
// ============================================================================

export const golangManagedFiles: Record<string, ManagedFileDefinition> = {
  '.golangci.yml': {
    generator: ctx =>
      !ctx.projectType.existingGolangciConfig && ctx.languages?.golang
        ? generateGolangciConfig()
        : undefined,
  },
};
