/**
 * Learning sync — generates `.safeword-project/learnings/INDEX.md` from the
 * `*.md` files in that folder so agents can navigate learnings via a
 * Karpathy-style LLM Wiki index (plain markdown + grep) without hitting the
 * Claude Code skill-description 1024-char cap.
 *
 * Ticket #130.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

export const LEARNINGS_RELATIVE_PATH = '.safeword-project/learnings';
export const INDEX_FILENAME = 'INDEX.md';

export interface LearningEntry {
  fileName: string;
  relativePath: string; // e.g. .safeword-project/learnings/foo.md
  title: string;
  covers: string; // topic list from the "Covers:" line
}

export interface SyncResult {
  wrote: boolean;
  entries: LearningEntry[];
  skipped: { fileName: string; reason: string }[];
  indexPath: string;
}

/**
 * Parse a single learning file. Returns the entry if it has a Covers: line
 * on line 3, or a reason string explaining why it was skipped.
 */
export function parseLearning(
  filePath: string,
): { ok: true; entry: Omit<LearningEntry, 'relativePath'> } | { ok: false; reason: string } {
  const content = readFileSync(filePath, 'utf8');
  const lines = content.split('\n');

  if (lines.length < 3) {
    return { ok: false, reason: 'file has fewer than 3 lines' };
  }

  const titleLine = lines[0] ?? '';
  const coversLine = lines[2] ?? '';

  if (!coversLine.startsWith('Covers:')) {
    return { ok: false, reason: 'missing Covers: line on line 3' };
  }

  const covers = coversLine.slice('Covers:'.length).trim();
  if (covers.length === 0) {
    return { ok: false, reason: 'Covers: line is empty' };
  }

  const title = titleLine.startsWith('# ')
    ? titleLine.slice(2).trim()
    : nodePath.basename(filePath, '.md');

  const fileName = nodePath.basename(filePath);
  return { ok: true, entry: { fileName, title, covers } };
}

/**
 * Read all learning files. Files lacking Covers: on line 3 are skipped.
 * INDEX.md itself is excluded from enumeration (it's the output, not an input).
 */
export function readLearnings(learningsDirectory: string): {
  entries: LearningEntry[];
  skipped: { fileName: string; reason: string }[];
} {
  if (!existsSync(learningsDirectory)) {
    return { entries: [], skipped: [] };
  }

  const entries: LearningEntry[] = [];
  const skipped: { fileName: string; reason: string }[] = [];

  const fileNames = readdirSync(learningsDirectory)
    .filter(name => name.endsWith('.md') && name !== INDEX_FILENAME)
    .toSorted((a, b) => a.localeCompare(b));

  for (const fileName of fileNames) {
    const filePath = nodePath.join(learningsDirectory, fileName);
    const parsed = parseLearning(filePath);
    if (parsed.ok) {
      entries.push({
        ...parsed.entry,
        relativePath: `${LEARNINGS_RELATIVE_PATH}/${fileName}`,
      });
    } else {
      skipped.push({ fileName, reason: parsed.reason });
    }
  }

  return { entries, skipped };
}

/**
 * Render the full INDEX.md contents for the learnings folder.
 * Deterministic: same entries → same bytes. No size cap — the agent reads
 * this file via the Read tool, which handles long markdown fine.
 */
export function buildIndexContent(entries: LearningEntry[]): string {
  const header = [
    '# Project Learnings — Index',
    '',
    '<!-- Auto-generated by `safeword sync-learnings`. Do not edit this file by hand. -->',
    '<!-- Edit source learning files in this folder; the index regenerates on save. -->',
    '',
  ];

  if (entries.length === 0) {
    return [
      ...header,
      'No learnings recorded yet. Add project-specific lessons to this folder',
      `with a \`Covers:\` line on line 3. See \`.safeword/guides/learning-extraction.md\``,
      'for when and how to extract.',
      '',
    ].join('\n');
  }

  const lines = [...header, `## Learnings (${entries.length})`, ''];
  for (const entry of entries) {
    lines.push(`- **${entry.title}** — ${entry.covers}`, `  → \`${entry.relativePath}\``);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Generate/update `.safeword-project/learnings/INDEX.md` from the learnings
 * folder. Returns whether bytes changed and any skipped entries.
 */
export function syncLearnings(cwd: string): SyncResult {
  const learningsDirectory = nodePath.join(cwd, LEARNINGS_RELATIVE_PATH);
  const indexPath = nodePath.join(learningsDirectory, INDEX_FILENAME);

  const { entries, skipped } = readLearnings(learningsDirectory);
  const nextContent = buildIndexContent(entries);

  // If there are no entries and the learnings directory doesn't exist, don't
  // create it just to write an empty-state index. No-op.
  if (entries.length === 0 && !existsSync(learningsDirectory)) {
    return { wrote: false, entries, skipped, indexPath };
  }

  const previousContent = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : undefined;
  if (previousContent === nextContent) {
    return { wrote: false, entries, skipped, indexPath };
  }

  writeFileSync(indexPath, nextContent);
  return { wrote: true, entries, skipped, indexPath };
}
