import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractScenarioReviewRubric } from '../src/review/scenario-rubric.js';
import {
  type GeneratedFileReconciliation,
  isDirectGeneratorInvocation,
  runGeneratedRubric,
} from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/review-spec/SKILL.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/scenario-rubric.generated.ts');
const rubric = extractScenarioReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-scenario-rubric.ts. Do not edit.',
  'export const SCENARIO_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

export function generateScenarioRubric(check = false): GeneratedFileReconciliation {
  return runGeneratedRubric({
    check,
    content: output,
    defaultOutputPath,
    generateCommand: 'generate:scenario-rubric',
    generatorEntrypoint: import.meta.filename,
    label: 'scenario-review',
  });
}

if (isDirectGeneratorInvocation(import.meta.filename)) {
  generateScenarioRubric(process.argv.includes('--check'));
}
