import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractExecutableRedRubric } from '../src/review/red-rubric.js';
import { generatedOutputPath, reconcileGeneratedFile } from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/tdd-review/SKILL.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/red-rubric.generated.ts');
const outputPath = generatedOutputPath(defaultOutputPath, import.meta.filename);
const rubric = extractExecutableRedRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-red-rubric.ts. Do not edit.',
  'export const EXECUTABLE_RED_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

const check = process.argv.includes('--check');
const staleMessage = `Generated executable RED rubric at ${outputPath} is stale; run generate:red-rubric`;
const reconciliation = reconcileGeneratedFile({
  check,
  content: output,
  outputPath,
});

if (reconciliation === 'stale') {
  console.error(staleMessage);
  process.exitCode = 1;
} else if (check) {
  console.log(`Generated executable RED runtime rubric at ${outputPath} is current.`);
} else if (reconciliation === 'current') {
  console.log('Executable RED runtime rubric is already current.');
} else {
  console.log('Generated the executable RED runtime rubric.');
}
