import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractExecutableRedRubric } from '../src/review/red-rubric.js';
import {
  type GeneratedFileReconciliation,
  isDirectGeneratorInvocation,
  runGeneratedRubric,
} from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/tdd-review/SKILL.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/red-rubric.generated.ts');
const rubric = extractExecutableRedRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-red-rubric.ts. Do not edit.',
  'export const EXECUTABLE_RED_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

export function generateRedRubric(check = false): GeneratedFileReconciliation {
  return runGeneratedRubric({
    check,
    content: output,
    defaultOutputPath,
    generateCommand: 'generate:red-rubric',
    generatorEntrypoint: import.meta.filename,
    label: 'executable RED',
  });
}

if (isDirectGeneratorInvocation(import.meta.filename)) {
  generateRedRubric(process.argv.includes('--check'));
}
