import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractExecutableRedRubric } from '../src/review/red-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/tdd-review/SKILL.md');
const outputPath = nodePath.join(packageRoot, 'src/review/red-rubric.generated.ts');
const rubric = extractExecutableRedRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-red-rubric.ts. Do not edit.',
  'export const EXECUTABLE_RED_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output)
    throw new Error('Generated executable RED rubric is stale; run generate:red-rubric');
  console.log('Generated executable RED review runtime rubric is current.');
} else {
  if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== output) {
    writeFileSync(outputPath, output);
  }
  console.log('Generated the executable RED review runtime rubric.');
}
