import { readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractPlanReviewRubric } from '../src/review/plan-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/bdd/PLAN_IMPLEMENTATION.md');
const outputPath = nodePath.join(packageRoot, 'src/review/plan-rubric.generated.ts');
const rubric = extractPlanReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-plan-rubric.ts. Do not edit.',
  `export const PLAN_REVIEW_RUBRIC = ${JSON.stringify(rubric)};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) {
    throw new Error('Generated plan-review rubric is stale; run generate:plan-rubric');
  }
  console.log('Generated plan-review runtime rubric is current.');
} else {
  writeFileSync(outputPath, output);
  console.log('Generated the plan-review runtime rubric.');
}
