import { readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractQualityReviewRubric } from '../src/review/quality-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/quality-review/SKILL.md');
const outputPath = nodePath.join(packageRoot, 'src/review/quality-rubric.generated.ts');
const rubric = extractQualityReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-quality-rubric.ts. Do not edit.',
  'export const QUALITY_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) {
    throw new Error('Generated quality-review rubric is stale; run generate:quality-rubric');
  }
  console.log('Generated quality-review runtime rubric is current.');
} else {
  writeFileSync(outputPath, output);
  console.log('Generated the quality-review runtime rubric.');
}
