import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractQualityReviewRubric } from '../src/review/quality-rubric.js';
import { runGeneratedRubric } from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/quality-review/SKILL.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/quality-rubric.generated.ts');
const rubric = extractQualityReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-quality-rubric.ts. Do not edit.',
  'export const QUALITY_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

runGeneratedRubric({
  content: output,
  defaultOutputPath,
  generateCommand: 'generate:quality-rubric',
  generatorEntrypoint: import.meta.filename,
  label: 'quality-review',
});
