import { readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractScenarioReviewRubric } from '../src/review/scenario-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/review-spec/SKILL.md');
const outputPath = nodePath.join(packageRoot, 'src/review/scenario-rubric.generated.ts');
const rubric = extractScenarioReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-scenario-rubric.ts. Do not edit.',
  `export const SCENARIO_REVIEW_RUBRIC = ${JSON.stringify(rubric)};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) {
    throw new Error('Generated scenario-review rubric is stale; run generate:scenario-rubric');
  }
  console.log('Generated scenario-review runtime rubric is current.');
} else {
  writeFileSync(outputPath, output);
  console.log('Generated the scenario-review runtime rubric.');
}
