import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractPlanReviewRubric } from '../src/review/plan-rubric.js';
import {
  type GeneratedFileReconciliation,
  isDirectGeneratorInvocation,
  runGeneratedRubric,
} from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/bdd/PLAN_IMPLEMENTATION.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/plan-rubric.generated.ts');
const rubric = extractPlanReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-plan-rubric.ts. Do not edit.',
  'export const PLAN_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

export function generatePlanRubric(check = false): GeneratedFileReconciliation {
  return runGeneratedRubric({
    check,
    content: output,
    defaultOutputPath,
    generateCommand: 'generate:plan-rubric',
    generatorEntrypoint: import.meta.filename,
    label: 'plan-review',
  });
}

if (isDirectGeneratorInvocation(import.meta.filename)) {
  generatePlanRubric(process.argv.includes('--check'));
}
