import { readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractExecutionPlanReviewRubric } from '../src/review/execution-plan-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const referencePath = nodePath.join(packageRoot, 'templates/skills/bdd/PLAN_EXECUTION.md');
const outputPath = nodePath.join(packageRoot, 'src/review/execution-plan-rubric.generated.ts');
const rubric = extractExecutionPlanReviewRubric(readFileSync(referencePath, 'utf8'));
const output = [
  '// Generated by scripts/generate-execution-plan-rubric.ts. Do not edit.',
  'export const EXECUTION_PLAN_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) {
    throw new Error(
      'Generated Execution Plan reviewer rubric is stale; run generate:execution-plan-rubric',
    );
  }
  console.log('Generated Execution Plan reviewer rubric is current.');
} else {
  if (readFileSync(outputPath, 'utf8') !== output) writeFileSync(outputPath, output);
  console.log('Generated the Execution Plan reviewer rubric.');
}
