import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

import { format, resolveConfig } from 'prettier';

import { extractDeliveryCompatibilityReviewRubric } from '../src/review/delivery-compatibility-rubric.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const referencePath = nodePath.join(packageRoot, 'templates/skills/bdd/PLAN_EXECUTION.md');
const outputPath = nodePath.join(
  packageRoot,
  'src/review/delivery-compatibility-rubric.generated.ts',
);
const rubric = extractDeliveryCompatibilityReviewRubric(readFileSync(referencePath, 'utf8'));
const unformatted = [
  '// Generated by scripts/generate-delivery-compatibility-rubric.ts. Do not edit.',
  'export const DELIVERY_COMPATIBILITY_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');
const prettierConfig = await resolveConfig(outputPath);
const output = await format(unformatted, { ...prettierConfig, parser: 'typescript' });

if (process.argv.includes('--check')) {
  if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== output) {
    throw new Error(
      'Generated delivery compatibility reviewer rubric is stale; run generate:delivery-compatibility-rubric',
    );
  }
  console.log('Generated delivery compatibility reviewer rubric is current.');
} else {
  if (!existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== output) {
    writeFileSync(outputPath, output);
  }
  console.log('Generated the delivery compatibility reviewer rubric.');
}
