import { readFileSync } from 'node:fs';
import nodePath from 'node:path';

import { extractPlanReviewRubric } from '../src/review/plan-rubric.js';
import { generatedOutputPath, reconcileGeneratedFile } from './lib/reconcile-generated-file.js';

const packageRoot = nodePath.resolve(import.meta.dirname, '..');
const skillPath = nodePath.join(packageRoot, 'templates/skills/bdd/PLAN_IMPLEMENTATION.md');
const defaultOutputPath = nodePath.join(packageRoot, 'src/review/plan-rubric.generated.ts');
const outputPath = generatedOutputPath(defaultOutputPath, import.meta.filename);
const rubric = extractPlanReviewRubric(readFileSync(skillPath, 'utf8'));
const output = [
  '// Generated by scripts/generate-plan-rubric.ts. Do not edit.',
  'export const PLAN_REVIEW_RUBRIC =',
  `  ${JSON.stringify(rubric)};`,
  '',
].join('\n');

const check = process.argv.includes('--check');
const staleMessage = `Generated plan-review rubric at ${outputPath} is stale; run generate:plan-rubric`;
const reconciliation = reconcileGeneratedFile({
  check,
  content: output,
  outputPath,
});

if (reconciliation === 'stale') {
  console.error(staleMessage);
  process.exitCode = 1;
} else if (check) {
  console.log(`Generated plan-review runtime rubric at ${outputPath} is current.`);
} else if (reconciliation === 'current') {
  console.log('Plan-review runtime rubric is already current.');
} else {
  console.log('Generated the plan-review runtime rubric.');
}
