// Generated by scripts/generate-claude-historical-catalogue.ts. Do not edit.
export const CLAUDE_HISTORICAL_CATALOGUE = {
  schema_version: 1,
  current: {
    files: {
      '.claude/agents/safeword-retro-filer.md':
        '0f4bc744e55e6e404dee4258b6180b111828ec833b66997ade79b0d159f7e8d4',
      '.claude/agents/safeword-reviewer.md':
        '5cc17d5cec1a6df812770cf80667673279bf1acc1bb961ebe458f8c5b58bdc1a',
      '.claude/skills/audit/SKILL.md':
        '784da329a70fe34b6e3a477b50caaee0d6bbfc1a3ed1d33b213fd9fb55346f4d',
      '.claude/skills/bdd/DISCOVERY.md':
        '057b81e87cf4857c780e01ebebdc278485d3179c249335fbc38264784f0587bb',
      '.claude/skills/bdd/DONE.md':
        'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
      '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
        '25643762cae499a802939df5d833f1f6bec502bc3c5b31156e8001646733d858',
      '.claude/skills/bdd/SCENARIOS.md':
        '2cf7c403e6a50c5ee1574f6e0a0965ee4afcbda9d0ec4580b425723ec5d4f83d',
      '.claude/skills/bdd/SKILL.md':
        'c80750fc562dd99f0d5a9fff31b772e36d4da6710c25be9ea3df0b958342b8b5',
      '.claude/skills/bdd/SPLITTING.md':
        'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
      '.claude/skills/bdd/TDD.md':
        'ddc1afadbd231fa0731503491f155f7b067e7fa4fb1a6858adbbb9e51ceddeff',
      '.claude/skills/bdd/VERIFY.md':
        '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
      '.claude/skills/brainstorm/SKILL.md':
        'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
      '.claude/skills/cleanup-zombies/SKILL.md':
        'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
      '.claude/skills/closeout/SKILL.md':
        '8f995e4e149223b730edbe718b8710837c26a4a1ad4daf5b40c0ba661fafc09d',
      '.claude/skills/debug/SKILL.md':
        'ae56c4c9287f76a2250d13fa9908f5726ed4edbe4080ece10d1559507e242bd0',
      '.claude/skills/elicit/SKILL.md':
        '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
      '.claude/skills/explain/SKILL.md':
        '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
      '.claude/skills/figure-it-out/SKILL.md':
        '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
      '.claude/skills/finish-review/REVIEWER.md':
        '1fdbcc909088278f39f69bb77efe49cf422333210e5b393f3a2a247e898e7efa',
      '.claude/skills/finish-review/SKILL.md':
        'b6be07deb9c444a9956a0fc1ac863d83727869c4377ca7a569ac43e480ed6618',
      '.claude/skills/lint/SKILL.md':
        '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
      '.claude/skills/quality-review/SKILL.md':
        'a244e013878d55fc20dcba1bfbbd8107306a5dce7c0018fd9bd5538d05bc70c1',
      '.claude/skills/refactor/SKILL.md':
        'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
      '.claude/skills/retro-filer/SKILL.md':
        '8e92f1a7579ba1dd70ced8e9815be0eeed3bc09d43c310a5646ff93c428412ff',
      '.claude/skills/retro/SKILL.md':
        '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
      '.claude/skills/review-spec/SKILL.md':
        'c16e547a95777665ac10984e2b798ba61200ba289de465b715c9b9d569b4ed7a',
      '.claude/skills/self-review/SKILL.md':
        '51bccc782884dc2ef6171465909df2726875bb308d0004fd2bbed13e51208ffc',
      '.claude/skills/spike/SKILL.md':
        '905aab56037ad5a258bafa91cb2ebf05cff1acffbc9e1fd6f7a1f27230672f37',
      '.claude/skills/tdd-review/SKILL.md':
        'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
      '.claude/skills/testing/SKILL.md':
        '697a4b090935989e0c8a53462d2b44087afafa50adc69e9a98da14bed23dbde9',
      '.claude/skills/ticket-system/SKILL.md':
        '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
      '.claude/skills/verify/SKILL.md':
        '71a6236f9522df0ac6d9f6627d4b66e57dc5067d71c0b64cd66da2cdf5c2f24c',
    },
    hooks: {
      SessionStart: [
        '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
        '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
        '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
        '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
        '1748d249b1ef227d313b5da2e098dd26c38b78a1de5bb8f6f236ba567420a17d',
        '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
        'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
        '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
        '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
        'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
        'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
      ],
      UserPromptSubmit: [
        'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
        '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
        'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
      ],
      Stop: [
        'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
        '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
        '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
        '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
        'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
      ],
      PreToolUse: [
        'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
        '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
        'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
        'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
        '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
        '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
        '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
        '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
      ],
      PostToolUse: [
        '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
        '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
        '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
        '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
        '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
        '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
        'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
      ],
      SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
    },
  },
  releases: {
    '0.68.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          'd0adabee189a52adac5bb79ef92e8fc8201cf69d89680ec1db96385722527aa1',
        '.claude/skills/audit/SKILL.md':
          '66de01380bd88cbc95b26888f23b70363a640262b6dab138531085be8194ca24',
        '.claude/skills/bdd/DISCOVERY.md':
          'b207684a7615f83df08e68d9e13660b2745e247e18f611bc9b606904bef4319b',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/SCENARIOS.md':
          '1be1365aa5dc1302bf10c5d74a6f50e28e28555b83e963e7257029d92a4910f4',
        '.claude/skills/bdd/SKILL.md':
          '75ed76b99df6fb818e3a63d9428d87b7228a2f136218d74bf1dc666b711be8cd',
        '.claude/skills/bdd/SPLITTING.md':
          '17367d157ebde2b2f9da04798615981527fe0cbb0da0fd5770818fd17adb88d8',
        '.claude/skills/bdd/TDD.md':
          '4f11431c53f377f309a2ee57d051c1f59557244ff92c3c0e07226e52f38e3ac1',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          '4fb21183502edd0806dc4a520b95b12c161294e69150f8c32f719095fc2e5f44',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '14f697e93d3f287caf5e2c0aa49b6ef20ee73da2faea7f6dc3f6eef7f79ee049',
        '.claude/skills/lint/SKILL.md':
          'd26d0f631e7fa8653e9fa110e139584049796979ee1638e3601059906cee6c78',
        '.claude/skills/quality-review/SKILL.md':
          '6c0e4891fb70e0371cc2268d671d8d802c46a08c986032ae55493d803d5b6dfb',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro/SKILL.md':
          'dfa8182df00d3d3935e475ec34de8b3f7fba2819065261bb8e595147434a1aeb',
        '.claude/skills/review-spec/SKILL.md':
          'cd61d4a6b22164cf1d14479553ada2502aacb8a36f137e59593ffdbd5540a91a',
        '.claude/skills/self-review/SKILL.md':
          'c6502e0e3a067e4ffbe641e09f9de224d538bede7695c7f9b829acb01497e3ac',
        '.claude/skills/tdd-review/SKILL.md':
          'b190130a5bdf3ce2a47fd955c20835db5d75911095b422ef0aecd4c97fa3df2f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '1531780c2e04a8a3bc9fd5b48735cc6b4a4b2faac59337a93975136b2c200eaa',
        '.claude/skills/verify/SKILL.md':
          '23900f59b8ba03fd4d5a0d49fbbe03f6fe54364d6eef009870e9a5694b97cd12',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.69.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          'd0adabee189a52adac5bb79ef92e8fc8201cf69d89680ec1db96385722527aa1',
        '.claude/skills/audit/SKILL.md':
          '5d532b2980976d758927ebf6e66a5e9022d83a421c936c378bca1391aa5d58a4',
        '.claude/skills/bdd/DISCOVERY.md':
          '9850364b48f66dc207cb9c8058f7564f70a5ac331a4bd188d71f3215c22d3dc4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'ae8fd9fe228b8005606414c339342a8ba15331511d1b6f90eaca7e608bf08c53',
        '.claude/skills/bdd/SCENARIOS.md':
          '59c07c9ad8914a60d879450e3ffe54cd79b199a652b70f7fa6156c7c87c27b60',
        '.claude/skills/bdd/SKILL.md':
          'ee1fbce1054cab1fd0263341925c546c0f7070afdd2dbc1b6d974ae02188cf8b',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '337c1c44e2b961da26de2a776fe599557b2ff2f606059b15fb5b948a1fa54c20',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          '4fb21183502edd0806dc4a520b95b12c161294e69150f8c32f719095fc2e5f44',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '14f697e93d3f287caf5e2c0aa49b6ef20ee73da2faea7f6dc3f6eef7f79ee049',
        '.claude/skills/lint/SKILL.md':
          'd26d0f631e7fa8653e9fa110e139584049796979ee1638e3601059906cee6c78',
        '.claude/skills/quality-review/SKILL.md':
          '100ebdf18b3bd4cdd8ef683c2cddf9f9bcd9e25dc82ef9f685f1e8dbbc630703',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro/SKILL.md':
          'dfa8182df00d3d3935e475ec34de8b3f7fba2819065261bb8e595147434a1aeb',
        '.claude/skills/review-spec/SKILL.md':
          'f643918f0da9c2b9d2c5b4675fd0096e441f1315c58f7b0d236b0ac6a1e71cbb',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/tdd-review/SKILL.md':
          '4243eec9ddf77780028b8aa19f362ced4fa51673575feeccd7fa658eb0bc6080',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          'f8312db9cf377906cef931e5e2a63917e76cffed5626c57dbf4a3239e7b0825a',
        '.claude/skills/verify/SKILL.md':
          '23900f59b8ba03fd4d5a0d49fbbe03f6fe54364d6eef009870e9a5694b97cd12',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.70.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'ae8fd9fe228b8005606414c339342a8ba15331511d1b6f90eaca7e608bf08c53',
        '.claude/skills/bdd/SCENARIOS.md':
          '379cb1f3ba62bfdb98c1f5383d7f460ac730371a34030b8879ab999b6e548585',
        '.claude/skills/bdd/SKILL.md':
          'ee1fbce1054cab1fd0263341925c546c0f7070afdd2dbc1b6d974ae02188cf8b',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          'e342a8fec91c403383f5ebce5c31c9eb4db555e77e56a6453b5b8ea0b97c118c',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.71.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'a86b45f577e530ce8ded59159960fbdba61243d36d61609bdbc52634e7613136',
        '.claude/skills/bdd/SCENARIOS.md':
          '1600df799059ea9d399f6a7bdd16c0f03be2cdd1f1f743595c350600a5d9ce5b',
        '.claude/skills/bdd/SKILL.md':
          '0d1f9498f74a39099cc61e578867226bcb149c96d09699ca7bafbc571873accb',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/spike/SKILL.md':
          '905aab56037ad5a258bafa91cb2ebf05cff1acffbc9e1fd6f7a1f27230672f37',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          '1980ba580e89d5c0ec1d47a6ff60aefd9d12a19922efbae18da61333a97bf13e',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.71.0-rc.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'ae8fd9fe228b8005606414c339342a8ba15331511d1b6f90eaca7e608bf08c53',
        '.claude/skills/bdd/SCENARIOS.md':
          '379cb1f3ba62bfdb98c1f5383d7f460ac730371a34030b8879ab999b6e548585',
        '.claude/skills/bdd/SKILL.md':
          'ee1fbce1054cab1fd0263341925c546c0f7070afdd2dbc1b6d974ae02188cf8b',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          'e342a8fec91c403383f5ebce5c31c9eb4db555e77e56a6453b5b8ea0b97c118c',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.71.0-rc.1': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'ae8fd9fe228b8005606414c339342a8ba15331511d1b6f90eaca7e608bf08c53',
        '.claude/skills/bdd/SCENARIOS.md':
          '379cb1f3ba62bfdb98c1f5383d7f460ac730371a34030b8879ab999b6e548585',
        '.claude/skills/bdd/SKILL.md':
          'ee1fbce1054cab1fd0263341925c546c0f7070afdd2dbc1b6d974ae02188cf8b',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          '1980ba580e89d5c0ec1d47a6ff60aefd9d12a19922efbae18da61333a97bf13e',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.71.0-rc.2': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'a86b45f577e530ce8ded59159960fbdba61243d36d61609bdbc52634e7613136',
        '.claude/skills/bdd/SCENARIOS.md':
          '1600df799059ea9d399f6a7bdd16c0f03be2cdd1f1f743595c350600a5d9ce5b',
        '.claude/skills/bdd/SKILL.md':
          '0d1f9498f74a39099cc61e578867226bcb149c96d09699ca7bafbc571873accb',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/spike/SKILL.md':
          '905aab56037ad5a258bafa91cb2ebf05cff1acffbc9e1fd6f7a1f27230672f37',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          '1980ba580e89d5c0ec1d47a6ff60aefd9d12a19922efbae18da61333a97bf13e',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.71.0-rc.3': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '562f68cdec41156ec1ea1a74a4041ddef225b34d66f29b87e34363c6952cffe9',
        '.claude/skills/audit/SKILL.md':
          '2653e4439921c4b53338159345001927df949d872c065c6c99aca5952c3444d4',
        '.claude/skills/bdd/DISCOVERY.md':
          'bab275004297553f0d16f65a7c6d2313c402886acd5f1ae2f4e6a1469dd1d1f4',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          'a86b45f577e530ce8ded59159960fbdba61243d36d61609bdbc52634e7613136',
        '.claude/skills/bdd/SCENARIOS.md':
          '1600df799059ea9d399f6a7bdd16c0f03be2cdd1f1f743595c350600a5d9ce5b',
        '.claude/skills/bdd/SKILL.md':
          '0d1f9498f74a39099cc61e578867226bcb149c96d09699ca7bafbc571873accb',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '3263c9b2b0f56d38080b6552e29ae26232d7f5a38085d883fff3593e84f55636',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '269b5236690afc80a3983cae7735d870500a6e51562ce39696030846159f764b',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '69784daf36495f00611e0057b6cc52a0ce0a0be4744c96d5ee37f784251cfb52',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          'c029ae859b5a2e7ae72bf47351695e1dc2d371d08874f323b6c8edaf79673b29',
        '.claude/skills/self-review/SKILL.md':
          '8536a465238363c25aaadb971745d2504e14552f6c2583a17691e4102b17b5a3',
        '.claude/skills/spike/SKILL.md':
          '905aab56037ad5a258bafa91cb2ebf05cff1acffbc9e1fd6f7a1f27230672f37',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          '1980ba580e89d5c0ec1d47a6ff60aefd9d12a19922efbae18da61333a97bf13e',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
    '0.72.0': {
      files: {
        '.claude/agents/safeword-retro-filer.md':
          '56ae79a72b5947b5a2ed319685232aac55d42deaf74decac11499b7082f2804f',
        '.claude/skills/audit/SKILL.md':
          '784da329a70fe34b6e3a477b50caaee0d6bbfc1a3ed1d33b213fd9fb55346f4d',
        '.claude/skills/bdd/DISCOVERY.md':
          '057b81e87cf4857c780e01ebebdc278485d3179c249335fbc38264784f0587bb',
        '.claude/skills/bdd/DONE.md':
          'e9f22430341cf225eaf58ef6335720c5033cb8f6779425d5740adc0ff80a5f60',
        '.claude/skills/bdd/PLAN_IMPLEMENTATION.md':
          '96ca374881b14d59631583c82b73d73a27a98e86ea93b38f8a630256b41e7814',
        '.claude/skills/bdd/SCENARIOS.md':
          '1600df799059ea9d399f6a7bdd16c0f03be2cdd1f1f743595c350600a5d9ce5b',
        '.claude/skills/bdd/SKILL.md':
          '7912523b42a4637ad67306b03bee00f711437b3f6aa63eff03359bc3f2d938a8',
        '.claude/skills/bdd/SPLITTING.md':
          'e232a37a4d76f0dfc51e65965c1e1b7f1572e0dedce0fb8c031e75bd6544a708',
        '.claude/skills/bdd/TDD.md':
          '6e33c42b4a12796de0f542f0317715b58fb16c22bf6797303563b40518d34357',
        '.claude/skills/bdd/VERIFY.md':
          '85abadfe756a3f391779fe500cd5c66597a33e0cab7fcef55f6b633b30818f31',
        '.claude/skills/brainstorm/SKILL.md':
          'fe99638bd1621cbd5fe3780a8d39023d4b175e3be2aef2e60d0ebe7558848f2e',
        '.claude/skills/cleanup-zombies/SKILL.md':
          'e0af9635774767cf36eb69726e11c642ec1dad42839c11407ea8ef60f89fc289',
        '.claude/skills/closeout/SKILL.md':
          'd612ee520e5d36ffc29d46e02e66c94b25d4d079bf9912d72f436830e317b460',
        '.claude/skills/debug/SKILL.md':
          '730bc2878af36eaaf7e91d34ab76c3bcd8d05820753eed42582d70c4822daaf5',
        '.claude/skills/elicit/SKILL.md':
          '2638c773ce241a886563d1db8abbee70d72edefa780f762c0ed095df0f65cee5',
        '.claude/skills/explain/SKILL.md':
          '6673eccef3a9e68659c4e4b81b1e63bf9da03b1ae802dc7d22f419cb7c65472d',
        '.claude/skills/figure-it-out/SKILL.md':
          '4552275007b0161037a1791233722a89dac16f963f55aab80fc7a9b6b37f67d4',
        '.claude/skills/lint/SKILL.md':
          '208ec54032cabdcb532d1070e5ef5f1fcd6f0f0bfe8daf08e4ecf007aa285f66',
        '.claude/skills/quality-review/SKILL.md':
          '641a12f6df44413424e247501fb22030b095336361bea1df0f1bbcbf5a6ae9ae',
        '.claude/skills/refactor/SKILL.md':
          'ecfd1b594e9a4c18387e6b9bc84a5bd1ded6b0b3df40a69271ba779ce2b7f122',
        '.claude/skills/retro-filer/SKILL.md':
          '85d200d86d8b20f17b99209b12de7a12cdd28713de98519e3febc3373d798519',
        '.claude/skills/retro/SKILL.md':
          '8e7b5912810c1e0fe596ff2367b5bc7d3890bd86db5719f49e3c0227b0fdd44a',
        '.claude/skills/review-spec/SKILL.md':
          '8aa2949e1f1197a77784770690a2b834acc0c95d30ef1adc61edd1bfd494eeed',
        '.claude/skills/self-review/SKILL.md':
          '51bccc782884dc2ef6171465909df2726875bb308d0004fd2bbed13e51208ffc',
        '.claude/skills/spike/SKILL.md':
          '905aab56037ad5a258bafa91cb2ebf05cff1acffbc9e1fd6f7a1f27230672f37',
        '.claude/skills/tdd-review/SKILL.md':
          'f49a7e07dea7a62f39e9919c0c4251ede4ec2dec72b9892e7e0c42205d510e6f',
        '.claude/skills/testing/SKILL.md':
          'e361b302f7a3f71ca6fdc30d65dbc6fc20bfeedaa012c489c3af96c20d1332d5',
        '.claude/skills/ticket-system/SKILL.md':
          '12798a8ebd1fb2bb65b4ee42fb3611d12f6817bc6cd27af829294ef31bfed27b',
        '.claude/skills/verify/SKILL.md':
          'e412319f4df946e146a377fb1581f4a6cc69faee92b4c25129593787506a2dd9',
      },
      hooks: {
        SessionStart: [
          '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0',
          '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0',
          '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff',
          '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007',
          '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33',
          'eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d',
          '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c',
          '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f',
          'f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923',
          '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d',
          'd3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8',
        ],
        UserPromptSubmit: [
          'c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082',
          '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c',
          'da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80',
        ],
        Stop: [
          'b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640',
          '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b',
          '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60',
          '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722',
          'fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429',
        ],
        PreToolUse: [
          'ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3',
          '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc',
          'b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20',
          'cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9',
          '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160',
          '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316',
          '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e',
          '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d',
        ],
        PostToolUse: [
          '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088',
          '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc',
          '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe',
          '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59',
          '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e',
          '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c',
          'ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823',
        ],
        SessionEnd: ['bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f'],
      },
    },
  },
  hook_entries: {
    '02e010df74c5114d87b115f0252fbda3a5dd8610fb5e7177c116a4cc9ea8c088': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-lint.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '1161ed35ca2d43cccf62773b926add8982e4bc8d375412a8ba5e9ca99c34241e': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-sync-learnings.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '167b3fe8cf355f66018c6c0f774b6d2e73ebecc81d4659701f9bfe45e1001722': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/stop-retro-filing.ts',
          type: 'command',
        },
      ],
    },
    '1748d249b1ef227d313b5da2e098dd26c38b78a1de5bb8f6f236ba567420a17d': {
      hooks: [
        {
          command:
            'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-reply-format.ts --agent=claude',
          type: 'command',
        },
      ],
    },
    '2d36e07ce195e76fa77dce0c3365269bcdd686d5130c39b9ba81b6b634e0b316': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-architecture-stage.ts',
          if: 'Bash(git commit*)',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    '2e0ec239ca638a9b4621493ef341d382054473fdac613fcbb876420a1b6fde59': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-bypass-warn.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '4537a8fa49d8fc6cb7b604789be118adc89ec6b69c56a2d2753c26ba408bb0fe': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-skill-nudge.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '49e2bc8bce947a8c427873963acab1bc872b11cda942e6a6617ec5af4d30a0cc': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-quality.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit|Bash',
    },
    '4d8bebe51f8e0160cbd954c539c217793362e4878dffbdb7b5a1cc527db4f33e': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-stale-main.ts',
          if: 'Bash(git checkout*)',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    '5fbab3be700e9ad4cd38aef9711316c1dc05fb202c818c5446c0cf1e9009b160': {
      hooks: [
        {
          command: 'bash "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-git-bare-fix.sh',
          if: 'Bash(git *)',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    '6208c493671fc67d1cd136ddd0a51de62175efce3498b902085373bc0ccc0db0': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-dependency-readiness.ts',
          type: 'command',
        },
      ],
    },
    '6988371a3718b3e8106f6758c4e71b180facb47eb4c6a9726a2e5318737feb60': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/stop-self-report.ts',
          type: 'command',
        },
      ],
    },
    '6a8b982c578e094444df4106084135358672b402f3dbed42d0860cdff163cf0c': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/prompt-questions.ts',
          type: 'command',
        },
      ],
    },
    '7a318d747884bb53ecc1d4578c79772ececfb786ae3c9cba823cafb3095a743c': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-work-log.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '8181faff2ffc1e802bb47d826b3649c94c83dbe33b22df9f60ed62275e66114d': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-stale-main.ts',
          if: 'Bash(git switch*)',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    '82821d39ad90cc6d81c5ac22a97e68ecafbba6cf1281ae1c875d0503a26f6d3f': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-author-model.ts',
          type: 'command',
        },
      ],
    },
    '83138a5df5610b37cb9dfd291b69fada684446e4dbdda0ddbab5a7e1dbf7c1ff': {
      hooks: [
        {
          asyncRewake: true,
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-auto-upgrade.ts',
          type: 'command',
        },
      ],
    },
    '839788553e5e540ab64361a8075fe397ecd46117cbef48696f6faba3648d1d2d': {
      hooks: [
        {
          command:
            'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-safeword-context.ts --agent=claude',
          type: 'command',
        },
      ],
      matcher: 'compact',
    },
    '8c7cf4fdb7cbecebcb4a9f3ec16cdf6aa777c1dfcf7110cb432798c86e31276c': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-architecture-heal.ts',
          type: 'command',
        },
      ],
    },
    '8d16ca09ac8148e614366f91b2f3dec1cef6925f96a17eacd24706269356978b': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/stop-reentry.ts',
          type: 'command',
        },
      ],
    },
    '921a0c53ce98ef7d84b1c6e4607f4703d1bda419fb6c813d0ed2925b0f16a9cc': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-quality.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    '98ed934c8e5cef5e3f94332b56968c980fde50fc79603e4dfe80ecaca49d77c0': {
      hooks: [
        {
          command: 'bash "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-bun-check.sh',
          type: 'command',
        },
      ],
    },
    '9dc99ba11055242f20b4f3c8944a382c2506931dcbdb6f99d97668b0afd70007': {
      hooks: [
        {
          command:
            'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-safeword-context.ts --agent=claude',
          type: 'command',
        },
      ],
    },
    '9ecd49f0d9143ba458f3db192dbe811184c6666ea3e74f9bf1d34d310dd0ba33': {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-version.ts',
          type: 'command',
        },
      ],
    },
    ada31831d8fc49b5b33bf72a5f0d47d883ca142a6f522fa2bbfff347174c07f3: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-dependency-readiness.ts',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    b8663c68fcb3cfa99a5eb61f521ac6ecca05aa4ff8d50f2502b2585845cff640: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/stop-quality.ts',
          type: 'command',
        },
      ],
    },
    b999d2b8223d74226377cc18ba5ae8e166586195c72208758ff115b91e2dce20: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-quality.ts',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    bdd68a3e1c4e47e615b9acd472a88bb884fdc38d85bd418e761b91682b339c7f: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-cleanup-quality.ts',
          type: 'command',
        },
      ],
    },
    c35e7daf8dce6e9de2ed10cb1793bc88096b6da9625b5901f3a6e944b5337082: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/prompt-timestamp.ts',
          type: 'command',
        },
      ],
    },
    cfbb47df37dd5dabe4c53b4ed922011b53f96310a3c7092f953bc34acae0cbd9: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/pre-tool-config-guard.ts',
          type: 'command',
        },
      ],
      matcher: 'Edit|Write|MultiEdit|NotebookEdit',
    },
    d3086b18bd08c1fc5779951d6d2162bf15ca2ccfc9ac689b7f38007bf27a1bc8: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-compact-context.ts',
          type: 'command',
        },
      ],
      matcher: 'compact',
    },
    da9392c2520f6de0f4f5a649a58b578b7115f3a06ae6fb161bc71da58913ec80: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/prompt-retro-nudge.ts',
          type: 'command',
        },
      ],
    },
    eaaf5018219f6868c77b5e78e40363a77fd3cd18f6d92890677196616d7ef97d: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-lint-check.ts',
          type: 'command',
        },
      ],
    },
    ebbc830c0c899a3ec0ab44564ae1db5e9566a2753b71e818bcd906c9bfdad823: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/post-tool-dependency-readiness.ts',
          type: 'command',
        },
      ],
      matcher: 'Bash',
    },
    f859fd42b853152ccfb4352e25d9b0c5026ab169d5c20291422395988e22e923: {
      hooks: [
        {
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/session-start-reentry.ts',
          type: 'command',
        },
      ],
    },
    fb64b381e9af34f6a19277b572e46f9069266073c12e93e6851893a6a34b5429: {
      hooks: [
        {
          async: true,
          command: 'bun "$CLAUDE_PROJECT_DIR"/.safeword/hooks/stop-retro.ts',
          type: 'command',
        },
      ],
    },
  },
} as const;
