import nodePath from 'node:path';

import { normalizePluginBundle } from '../../src/plugin-bundle.js';
import { requirePinnedBunVersion } from '../bun-version.js';

export { normalizePluginBundle as normalizePluginCliBundle } from '../../src/plugin-bundle.js';

export async function buildPluginCliBundle(
  packageRoot: string,
  packageManager: string,
  pluginName: string,
  builtVersion?: string,
): Promise<string> {
  // @ts-expect-error -- plugin generators execute under Bun; the CLI's
  // Node-targeted tsconfig intentionally does not expose Bun globals elsewhere.
  requirePinnedBunVersion(packageManager, Bun.version);

  // @ts-expect-error -- plugin generators execute under Bun.
  const result = await Bun.build({
    entrypoints: [nodePath.join(packageRoot, 'src', 'cli.ts')],
    // Keep generated bytes independent of the caller. Bun otherwise inlines
    // ambient NODE_ENV, so running a generator under Vitest can seal test-only
    // behavior into a bundle that differs from a normal release shell.
    define: {
      'process.env.NODE_ENV': JSON.stringify('development'),
      ...(builtVersion !== undefined && {
        __SAFEWORD_VERSION__: JSON.stringify(builtVersion),
      }),
    },
    format: 'esm',
    packages: 'bundle',
    splitting: false,
    target: 'bun',
    write: false,
  });
  if (!result.success || result.outputs.length !== 1 || result.outputs[0] === undefined) {
    throw new Error(`Failed to bundle the ${pluginName} plugin CLI: ${result.logs.join('\n')}`);
  }
  return normalizePluginBundle(await result.outputs[0].text());
}
