import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import nodePath from 'node:path';

interface ReconcileGeneratedFileOptions {
  check: boolean;
  content: string;
  outputPath: string;
}

export type GeneratedFileReconciliation = 'current' | 'stale' | 'updated';

interface GeneratedRubricOptions {
  check: boolean;
  content: string;
  defaultOutputPath: string;
  generateCommand: string;
  generatorEntrypoint: string;
  label: string;
}

interface GeneratedRubricDefinition {
  digestExportName?: string;
  exportName: string;
  extract: (source: string) => string;
  generateCommand: string;
  generatorEntrypoint: string;
  label: string;
  output: string;
  source: string;
}

export function isDirectGeneratorInvocation(generatorEntrypoint: string): boolean {
  const invokedEntrypoint = process.argv[1];
  if (invokedEntrypoint === undefined) return false;
  try {
    return realpathSync(invokedEntrypoint) === realpathSync(generatorEntrypoint);
  } catch {
    return false;
  }
}

/** Resolve a direct generator's optional output without consuming an importing script's argv. */
function generatedOutputPath(defaultPath: string, generatorEntrypoint: string): string {
  if (!isDirectGeneratorInvocation(generatorEntrypoint)) return defaultPath;

  let outputPath = defaultPath;
  for (let index = 2; index < process.argv.length; index += 1) {
    const argument = process.argv[index];
    if (argument === '--check') continue;
    if (argument !== '--output') throw new Error(`Unknown argument: ${argument}`);
    const requestedPath = process.argv[index + 1];
    if (requestedPath === undefined || requestedPath.startsWith('-')) {
      throw new Error('--output requires a path');
    }
    outputPath = nodePath.resolve(requestedPath);
    index += 1;
  }
  return outputPath;
}

/** Verify generated output in check mode, or update it without touching an identical file. */
export function reconcileGeneratedFile({
  check,
  content,
  outputPath,
}: ReconcileGeneratedFileOptions): GeneratedFileReconciliation {
  const stale = !existsSync(outputPath) || readFileSync(outputPath, 'utf8') !== content;
  if (check) return stale ? 'stale' : 'current';
  if (!stale) return 'current';
  mkdirSync(nodePath.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
  return 'updated';
}

/** Define one rubric generator from the source-to-export details that vary by rubric. */
export function defineGeneratedRubric(
  definition: GeneratedRubricDefinition,
): (check?: boolean) => GeneratedFileReconciliation {
  const packageRoot = nodePath.resolve(nodePath.dirname(definition.generatorEntrypoint), '..');
  const rubric = definition.extract(
    readFileSync(nodePath.join(packageRoot, definition.source), 'utf8'),
  );
  const digest = createHash('sha256').update(rubric).digest('hex');
  const content = [
    `// Generated by scripts/${nodePath.basename(definition.generatorEntrypoint)}. Do not edit.`,
    `export const ${definition.exportName} =`,
    `  ${JSON.stringify(rubric)};`,
    ...(definition.digestExportName === undefined
      ? []
      : [`export const ${definition.digestExportName} = ${JSON.stringify(digest)};`]),
    '',
  ].join('\n');

  return (check = false) =>
    runGeneratedRubric({
      check,
      content,
      defaultOutputPath: nodePath.join(packageRoot, definition.output),
      generateCommand: definition.generateCommand,
      generatorEntrypoint: definition.generatorEntrypoint,
      label: definition.label,
    });
}

/** Reconcile one generated runtime rubric and report its stable CLI result. */
function runGeneratedRubric(options: GeneratedRubricOptions): GeneratedFileReconciliation {
  const outputPath = generatedOutputPath(options.defaultOutputPath, options.generatorEntrypoint);
  const reconciliation = reconcileGeneratedFile({
    check: options.check,
    content: options.content,
    outputPath,
  });
  const description = `Generated ${options.label} runtime rubric at ${outputPath}`;

  if (reconciliation === 'stale') {
    console.error(`${description} is stale; run ${options.generateCommand}`);
    process.exitCode = 1;
  } else if (options.check) {
    console.log(`${description} is current.`);
  } else if (reconciliation === 'current') {
    const sentenceLabel = `${options.label[0]?.toUpperCase()}${options.label.slice(1)}`;
    console.log(`${sentenceLabel} runtime rubric is already current.`);
  } else {
    console.log(`Generated the ${options.label} runtime rubric.`);
  }
  return reconciliation;
}
